name: Fetch Dev.to Articles

on:
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - gh-page  # or your default branch

jobs:
  fetch-articles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Fetch Dev.to articles
        run: |
          mkdir -p assets/data
          curl -s "https://dev.to/api/articles?username=muktadirmaashif" > assets/data/devto-articles.json

      # - name: Commit and push if changes
      #   run: |
      #     git config --global user.name 'GitHub Action'
      #     git config --global user.email 'action@github.com'
      #     git add assets/data/devto-articles.json
      #     git diff --quiet && git diff --staged --quiet || (git commit -m "Update Dev.to articles data" && git push)
